export const TEMP_KUKIES = [
  {
    id: 1,
    writer: 'devbuzz142',
    content: '쿠키1',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 0,
    left: 100,
  },
  {
    id: 2,
    writer: 'devbuzz142',
    content: '쿠키2',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 2,
    left: 300,
  },
  {
    id: 3,
    writer: 'devbuzz142',
    content: '쿠키2',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 2,
    left: 0,
  },
  {
    id: 4,
    writer: 'devbuzz142',
    content: '쿠키2',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 5,
    left: 100,
  },
  {
    id: 5,
    writer: 'devbuzz142',
    content: '쿠키2',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 0,
    left: 600,
  },
];
