import kuki1 from '../assets/kuki_images/kuki_01.png';
import kuki2 from '../assets/kuki_images/kuki_02.png';

export const TEMP_KUKIES = [
  {
    id: 1,
    writer: 'devbuzz142',
    content: '쿠키1',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 0,
    left: 100,
    image: kuki1,
  },
  {
    id: 2,
    writer: 'devbuzz142',
    content: '쿠키2',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 2,
    left: 300,
    image: kuki2,
  },
  {
    id: 2,
    writer: 'devbuzz142',
    content: '쿠키2',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 2,
    left: 300,
    image: kuki2,
  },
  {
    id: 3,
    writer: 'devbuzz142',
    content: '쿠키2',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 2,
    left: 0,
    image: kuki2,
  },
  {
    id: 4,
    writer: 'devbuzz142',
    content: '쿠키2',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 5,
    left: 100,
    image: kuki1,
  },
  {
    id: 5,
    writer: 'devbuzz142',
    content: '쿠키2',
    isPublic: true,
    isAnonymous: false,
    isLike: false,
    likeCount: 0,
    left: 600,
    image: kuki1,
  },
];
